import { Comic_Neue } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";

const comicNeue = Comic_Neue({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${comicNeue.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Navbar></Navbar>
        {children}
        <Footer></Footer>

        <Toaster></Toaster>

      </body>
    </html>
  );
}
